name: validate

on:
  push

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: wordweaver validate
        run: wordweaver validate
